require 'rubygems'
require 'capistrano/ext/multistage'
require 'capistrano/confirm'
require 'capistrano/cowboy'
require 'capistrano_colors'
require 'railsless-deploy'
require './config/ec2'
load 'deploy' if respond_to?(:namespace) # cap2 differentiator
load './config/employees'
# load './config/email_util'
load './config/db'
# load './config/cron'
load 'config/deploy'
load './config/assets'
